# Generated by Django 6.1.1 on 2026-10-02 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.CharField(max_length=300)),
                (
                    "notas",
                    models.CharField(
                        help_text="Ex: coco, maracujá, baunilha", max_length=200
                    ),
                ),
                (
                    "familia",
                    models.CharField(
                        choices=[
                            ("FRU", "Frutal"),
                            ("FLO", "Floral"),
                            ("GOU", "Gourmand"),
                            ("CIT", "Cítrica"),
                            ("AQU", "Aquática"),
                            ("SOL", "Solar"),
                        ],
                        default="FRU",
                        max_length=3,
                    ),
                ),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                ("imagem_url", models.URLField(blank=True)),
                (
                    "destaque",
                    models.BooleanField(default=False, help_text="Aparece na Home"),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Mistura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.CharField(blank=True, max_length=300)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misturas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfumes",
                    models.ManyToManyField(related_name="misturas", to="nova.perfume"),
                ),
            ],
            options={
                "verbose_name_plural": "misturas",
                "ordering": ["-criado_em"],
            },
        ),
    ]
