# Generated by Django 6.1.1 on 2026-10-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfume",
            name="estoque",
            field=models.PositiveIntegerField(
                default=10, help_text="Unidades disponíveis"
            ),
        ),
    ]
