# Generated by Django 6.1.1 on 2026-10-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0002_perfume_estoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfume",
            name="imagem",
            field=models.CharField(
                blank=True,
                help_text="Nome do arquivo em static/img, ex: solaris.jpg",
                max_length=100,
            ),
        ),
    ]
