# Generated by Django 6.1.1 on 2026-10-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0003_perfume_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfume",
            name="familia",
            field=models.CharField(
                choices=[
                    ("FRU", "Frutal"),
                    ("FLO", "Floral"),
                    ("GOU", "Gourmand"),
                    ("CIT", "Cítrica"),
                    ("AQU", "Aquática"),
                    ("SOL", "Solar"),
                    ("ÉCL", "Éclat"),
                    ("NOC", "Nocturne"),
                ],
                default="FRU",
                max_length=3,
            ),
        ),
    ]
