# Generated by Django 6.1.1 on 2026-10-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0004_alter_perfume_familia"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfume",
            name="imagem_detalhe",
            field=models.CharField(
                blank=True,
                help_text="Imagem ao passar o mouse, ex: solaris-detalhes.jpg",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="video",
            field=models.CharField(
                blank=True,
                help_text="Vídeo do banner da Home (arquivo em static/video), ex: solaris.mp4",
                max_length=100,
            ),
        ),
    ]
